// src/with-react.tsx
import React, { ReactElement } from "react";
import ReactDOM from "react-dom";
import type { Component } from "@/src/core";

export const withReact = (element: ReactElement): Component => ({
  script: {
    onMount(root) {
      ReactDOM.render(<React.StrictMode>{element}</React.StrictMode>, root);
    },
  },
});

// src/with-vue.tsx
import type { Component } from "@/src/core";
import { createApp } from "vue";

export const withVue = (
  element: Parameters<typeof createApp>[0]
): Component => ({
  script: {
    onMount(root) {
      const el = document.createElement("div");
      root.appendChild(el);
      createApp(element).mount(el);
    },
  },
});
